apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bxc9l9u4e-nodejs-gitops
  description: This is GitOps manifest for bxc9l9u4e-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: bxc9l9u4e-nodejs
    janus-idp.io/tekton: bxc9l9u4e-nodejs 
    backstage.io/kubernetes-id: bxc9l9u4e-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bxc9l9u4e-nodejs
