apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bxc9l9u4e-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bxc9l9u4e-nodejs 
  name: bxc9l9u4e-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bxc9l9u4e-nodejs 
